name: Build & Test MCUXpresso SDK Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker container
        run: |
          docker build -t mcuxpresso-sdk .

      - name: Run container and initialize SDK with custom manifest
        run: |
          docker run --rm mcuxpresso-sdk bash -c "
          cd /workspace/mcuxsdk-manifests &&
          west init -l --mf /workspace/custom_west.yml . &&
          west update"

      - name: Build the application
        run: |
          docker run --rm mcuxpresso-sdk bash -c "
          cd /workspace/my_app &&
          west build -b your_board"

      - name: Store Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: /workspace/my_app/build/output/