name: Build & Test MCUXpresso SDK Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker container
        run: |
          docker build -t mcuxpresso-sdk .

      - name: Build the application inside container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace mcuxpresso-sdk bash -c "
            cd /workspace/project && \
            west build -b <your_board_name>
          "

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: project/build/
name: Build & Test MCUXpresso SDK Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker container
        run: |
          docker build -t mcuxpresso-sdk .

      - name: Build the application inside container
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace mcuxpresso-sdk bash -c "
            cd /workspace/project && \
            west build -b frdmmcxa153
          "

      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: project/build/
